name: build-bin

on: 
  workflow_dispatch:
    inputs:
      revision:
        description: 'svn revision'
        required: true
        default: 'r53879'
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 9999
    strategy:
      matrix:
        #profile: [k2p-mt76, k2p-mini, k2p, dir-882-a1, dir-882-r1, msg1500, a040wq]
        profile: [msg1500]
        
        
    steps:
      - uses: actions/checkout@v4
      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.profile }}
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl binwalk
          mkdir hh
          cd hh
          wget https://breed.hackpascal.net/breed-ar9331.bin
          binwalk breed-ar9331.bin
          dd if=breed.bin of=boot bs=1 count=12828
          dd if=breed.bin of=packed_data.lzma bs=1 skip=12828
          lzmainfo packed_data.lzma
          lzma -v -d packed_data.lzma -c >> unpacked_data

          
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
