name: build

on: 
  workflow_dispatch:
    inputs:
      revision:
        description: 'svn revision'
        required: true
        default: 'r53879'
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        #profile: [k2p-mt76, k2p-mini, k2p, dir-882-a1, dir-882-r1, msg1500, a040wq]
        profile: [msg1500]
    steps:
      - uses: actions/checkout@v4
      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.profile }}
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext gengetopt gtk-doc-tools \
            autoconf-archive automake autopoint meson texinfo build-essential help2man pkg-config \
            zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true
      - name: Install npm packages
        run: sudo npm install -g uglify-js uglifycss
      - name: Extract toolchain
        run: tar zxf toolchain-mipsel_24kc_gcc-13.1.0_musl.tar.gz
      - name: Prepare
        run: |
          echo PROFILE=${{ matrix.profile }} > .config
          echo REVISION=${{ github.event.inputs.revision }} >> .config
          make checkout
          make prepare
      - name: Configure
        run: make configure
      - name: Build
        run: make all
      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: images/*.bin
