name: netgear

on: 
  workflow_dispatch:
    inputs:
      publish:
        description: 'publish build result to a release'
        required: true
        type: boolean
  schedule:
    - cron: '30 21 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        drv: [r6220]  # Change to the relevant driver for NETGEAR R6220
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1.2
        with:
          append-timestamp: false
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext gengetopt gtk-doc-tools \
            automake autopoint meson texinfo build-essential help2man pkg-config zlib1g-dev \
            libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
          sudo apt install uglifyjs npm && sudo npm install uglifycss
       - uses: actions/setup-node@v4
        with:
          node-version: 18
          check-latest: true
      - name: Install npm packages
        run: sudo npm install -g uglify-js uglifycss
      - name: Extract toolchain
        run: tar zxf toolchain-mipsel_24kc_gcc-13.1.0_musl.tar.gz
      - name: Prepare
        run: |
          echo PROFILE=${{ matrix.profile }} > .config
          echo REVISION=${{ github.event.inputs.revision }} >> .config
          make checkout
          make prepare
      - name: Configure
        run: make configure
      - name: Build
        run: make all
      - uses: actions/upload-artifact@v3
        with:
          name: images
          path: images/*.bin
